#!/bin/bash
# ARACNE-AP network inference — GSE51092 (whole peripheral blood, 222 samples)
# Requires: Java, ARACNe-AP jar (https://github.com/califano-lab/ARACNe-AP)
# Input:    data/SJS_matrix.txt  — tab-delimited expression matrix (genes x samples,
#                                   cases only, no metadata rows), generated from
#                                   GSE51092 after QC and probe collapse
#           data/TFs_Lambert2018.txt — generated by mra_GSE84844.R
# Output:   data/sjs_network.txt — consolidated network used by mra_GSE51092.R
# Runtime:  ~2–4 h with 75 cores / 300 GB RAM; adjust N_CORES and MEM as needed

set -euo pipefail

ARACNE=/path/to/ARACNe-AP/dist/aracne.jar   # <-- set path to aracne.jar
EXPFILE=data/SJS_matrix.txt
TFFILE=data/TFs_Lambert2018.txt
OUTDIR=data/aracne_ap_output
N_BOOTSTRAPS=100
N_CORES=75
MEM=4G

mkdir -p "$OUTDIR"

java -Xmx${MEM} -jar "$ARACNE" \
    -e "$EXPFILE" -o "$OUTDIR" --tfs "$TFFILE" \
    --pvalue 1E-8 --seed 1 --calculateThreshold

seq 1 "$N_BOOTSTRAPS" | xargs -P "$N_CORES" -I{} \
    java -Xmx${MEM} -jar "$ARACNE" \
        -e "$EXPFILE" -o "$OUTDIR" --tfs "$TFFILE" \
        --pvalue 1E-8 --seed {}

java -Xmx${MEM} -jar "$ARACNE" \
    -e "$EXPFILE" -o "$OUTDIR" --consolidate

cp "$OUTDIR/network.txt" data/sjs_network.txt
